/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ClientRouteImport } from './routes/client'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CreatorRouteImport } from './routes/creator'
import { Route as CreatorApplyRouteImport } from './routes/creator-apply'
import { Route as CreatorsRouteImport } from './routes/creators'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as CreatorIndexRouteImport } from './routes/creator/index'
import { Route as AdminAuditLogsIndexRouteImport } from './routes/admin/audit-logs/index'
import { Route as AdminClientsIndexRouteImport } from './routes/admin/clients/index'
import { Route as AdminCreatorApplicationsIndexRouteImport } from './routes/admin/creator-applications/index'
import { Route as AdminCreatorApplicationsIdRouteImport } from './routes/admin/creator-applications/$id'
import { Route as AdminCreatorTiersIndexRouteImport } from './routes/admin/creator-tiers/index'
import { Route as AdminCreatorsIndexRouteImport } from './routes/admin/creators/index'
import { Route as AdminCreatorsIdRouteImport } from './routes/admin/creators/$id'
import { Route as AdminProjectsIndexRouteImport } from './routes/admin/projects/index'
import { Route as CreatorEarningsIndexRouteImport } from './routes/creator/earnings/index'
import { Route as CreatorNotificationsIndexRouteImport } from './routes/creator/notifications/index'
import { Route as CreatorPortfolioIndexRouteImport } from './routes/creator/portfolio/index'
import { Route as CreatorProfileIndexRouteImport } from './routes/creator/profile/index'
import { Route as CreatorProjectsIndexRouteImport } from './routes/creator/projects/index'
import { Route as CreatorServicesIndexRouteImport } from './routes/creator/services/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRoute = CreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorApplyRoute = CreatorApplyRouteImport.update({
  id: '/creator-apply',
  path: '/creator-apply',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsRoute = CreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CreatorIndexRoute = CreatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreatorRoute,
} as any)
const AdminAuditLogsIndexRoute = AdminAuditLogsIndexRouteImport.update({
  id: '/audit-logs/',
  path: '/audit-logs/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsIndexRoute = AdminClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCreatorApplicationsIndexRoute =
  AdminCreatorApplicationsIndexRouteImport.update({
    id: '/creator-applications/',
    path: '/creator-applications/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCreatorApplicationsIdRoute =
  AdminCreatorApplicationsIdRouteImport.update({
    id: '/creator-applications/$id',
    path: '/creator-applications/$id',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCreatorTiersIndexRoute = AdminCreatorTiersIndexRouteImport.update({
  id: '/creator-tiers/',
  path: '/creator-tiers/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCreatorsIndexRoute = AdminCreatorsIndexRouteImport.update({
  id: '/creators/',
  path: '/creators/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCreatorsIdRoute = AdminCreatorsIdRouteImport.update({
  id: '/creators/$id',
  path: '/creators/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsIndexRoute = AdminProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AdminRoute,
} as any)
const CreatorEarningsIndexRoute = CreatorEarningsIndexRouteImport.update({
  id: '/earnings/',
  path: '/earnings/',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorNotificationsIndexRoute =
  CreatorNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => CreatorRoute,
  } as any)
const CreatorPortfolioIndexRoute = CreatorPortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorProfileIndexRoute = CreatorProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorProjectsIndexRoute = CreatorProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorServicesIndexRoute = CreatorServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => CreatorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRoute
  '/contact': typeof ContactRoute
  '/creator': typeof CreatorRouteWithChildren
  '/creator-apply': typeof CreatorApplyRoute
  '/creators': typeof CreatorsRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/admin/': typeof AdminIndexRoute
  '/creator/': typeof CreatorIndexRoute
  '/admin/creator-applications/$id': typeof AdminCreatorApplicationsIdRoute
  '/admin/creators/$id': typeof AdminCreatorsIdRoute
  '/admin/audit-logs/': typeof AdminAuditLogsIndexRoute
  '/admin/clients/': typeof AdminClientsIndexRoute
  '/admin/creator-applications/': typeof AdminCreatorApplicationsIndexRoute
  '/admin/creator-tiers/': typeof AdminCreatorTiersIndexRoute
  '/admin/creators/': typeof AdminCreatorsIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/creator/earnings/': typeof CreatorEarningsIndexRoute
  '/creator/notifications/': typeof CreatorNotificationsIndexRoute
  '/creator/portfolio/': typeof CreatorPortfolioIndexRoute
  '/creator/profile/': typeof CreatorProfileIndexRoute
  '/creator/projects/': typeof CreatorProjectsIndexRoute
  '/creator/services/': typeof CreatorServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/client': typeof ClientRoute
  '/contact': typeof ContactRoute
  '/creator-apply': typeof CreatorApplyRoute
  '/creators': typeof CreatorsRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AdminIndexRoute
  '/creator': typeof CreatorIndexRoute
  '/admin/creator-applications/$id': typeof AdminCreatorApplicationsIdRoute
  '/admin/creators/$id': typeof AdminCreatorsIdRoute
  '/admin/audit-logs': typeof AdminAuditLogsIndexRoute
  '/admin/clients': typeof AdminClientsIndexRoute
  '/admin/creator-applications': typeof AdminCreatorApplicationsIndexRoute
  '/admin/creator-tiers': typeof AdminCreatorTiersIndexRoute
  '/admin/creators': typeof AdminCreatorsIndexRoute
  '/admin/projects': typeof AdminProjectsIndexRoute
  '/creator/earnings': typeof CreatorEarningsIndexRoute
  '/creator/notifications': typeof CreatorNotificationsIndexRoute
  '/creator/portfolio': typeof CreatorPortfolioIndexRoute
  '/creator/profile': typeof CreatorProfileIndexRoute
  '/creator/projects': typeof CreatorProjectsIndexRoute
  '/creator/services': typeof CreatorServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRoute
  '/contact': typeof ContactRoute
  '/creator': typeof CreatorRouteWithChildren
  '/creator-apply': typeof CreatorApplyRoute
  '/creators': typeof CreatorsRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/admin/': typeof AdminIndexRoute
  '/creator/': typeof CreatorIndexRoute
  '/admin/creator-applications/$id': typeof AdminCreatorApplicationsIdRoute
  '/admin/creators/$id': typeof AdminCreatorsIdRoute
  '/admin/audit-logs/': typeof AdminAuditLogsIndexRoute
  '/admin/clients/': typeof AdminClientsIndexRoute
  '/admin/creator-applications/': typeof AdminCreatorApplicationsIndexRoute
  '/admin/creator-tiers/': typeof AdminCreatorTiersIndexRoute
  '/admin/creators/': typeof AdminCreatorsIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/creator/earnings/': typeof CreatorEarningsIndexRoute
  '/creator/notifications/': typeof CreatorNotificationsIndexRoute
  '/creator/portfolio/': typeof CreatorPortfolioIndexRoute
  '/creator/profile/': typeof CreatorProfileIndexRoute
  '/creator/projects/': typeof CreatorProjectsIndexRoute
  '/creator/services/': typeof CreatorServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/client'
    | '/contact'
    | '/creator'
    | '/creator-apply'
    | '/creators'
    | '/login'
    | '/pricing'
    | '/register'
    | '/admin/'
    | '/creator/'
    | '/admin/creator-applications/$id'
    | '/admin/creators/$id'
    | '/admin/audit-logs/'
    | '/admin/clients/'
    | '/admin/creator-applications/'
    | '/admin/creator-tiers/'
    | '/admin/creators/'
    | '/admin/projects/'
    | '/creator/earnings/'
    | '/creator/notifications/'
    | '/creator/portfolio/'
    | '/creator/profile/'
    | '/creator/projects/'
    | '/creator/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/client'
    | '/contact'
    | '/creator-apply'
    | '/creators'
    | '/login'
    | '/pricing'
    | '/register'
    | '/admin'
    | '/creator'
    | '/admin/creator-applications/$id'
    | '/admin/creators/$id'
    | '/admin/audit-logs'
    | '/admin/clients'
    | '/admin/creator-applications'
    | '/admin/creator-tiers'
    | '/admin/creators'
    | '/admin/projects'
    | '/creator/earnings'
    | '/creator/notifications'
    | '/creator/portfolio'
    | '/creator/profile'
    | '/creator/projects'
    | '/creator/services'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/client'
    | '/contact'
    | '/creator'
    | '/creator-apply'
    | '/creators'
    | '/login'
    | '/pricing'
    | '/register'
    | '/admin/'
    | '/creator/'
    | '/admin/creator-applications/$id'
    | '/admin/creators/$id'
    | '/admin/audit-logs/'
    | '/admin/clients/'
    | '/admin/creator-applications/'
    | '/admin/creator-tiers/'
    | '/admin/creators/'
    | '/admin/projects/'
    | '/creator/earnings/'
    | '/creator/notifications/'
    | '/creator/portfolio/'
    | '/creator/profile/'
    | '/creator/projects/'
    | '/creator/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ClientRoute: typeof ClientRoute
  ContactRoute: typeof ContactRoute
  CreatorRoute: typeof CreatorRouteWithChildren
  CreatorApplyRoute: typeof CreatorApplyRoute
  CreatorsRoute: typeof CreatorsRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator': {
      id: '/creator'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof CreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator-apply': {
      id: '/creator-apply'
      path: '/creator-apply'
      fullPath: '/creator-apply'
      preLoaderRoute: typeof CreatorApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators': {
      id: '/creators'
      path: '/creators'
      fullPath: '/creators'
      preLoaderRoute: typeof CreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/creator/': {
      id: '/creator/'
      path: '/'
      fullPath: '/creator/'
      preLoaderRoute: typeof CreatorIndexRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/admin/audit-logs/': {
      id: '/admin/audit-logs/'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs/'
      preLoaderRoute: typeof AdminAuditLogsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients/': {
      id: '/admin/clients/'
      path: '/clients'
      fullPath: '/admin/clients/'
      preLoaderRoute: typeof AdminClientsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/creator-applications/': {
      id: '/admin/creator-applications/'
      path: '/creator-applications'
      fullPath: '/admin/creator-applications/'
      preLoaderRoute: typeof AdminCreatorApplicationsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/creator-applications/$id': {
      id: '/admin/creator-applications/$id'
      path: '/creator-applications/$id'
      fullPath: '/admin/creator-applications/$id'
      preLoaderRoute: typeof AdminCreatorApplicationsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/creator-tiers/': {
      id: '/admin/creator-tiers/'
      path: '/creator-tiers'
      fullPath: '/admin/creator-tiers/'
      preLoaderRoute: typeof AdminCreatorTiersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/creators/': {
      id: '/admin/creators/'
      path: '/creators'
      fullPath: '/admin/creators/'
      preLoaderRoute: typeof AdminCreatorsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/creators/$id': {
      id: '/admin/creators/$id'
      path: '/creators/$id'
      fullPath: '/admin/creators/$id'
      preLoaderRoute: typeof AdminCreatorsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects/': {
      id: '/admin/projects/'
      path: '/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AdminProjectsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/creator/earnings/': {
      id: '/creator/earnings/'
      path: '/earnings'
      fullPath: '/creator/earnings/'
      preLoaderRoute: typeof CreatorEarningsIndexRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/notifications/': {
      id: '/creator/notifications/'
      path: '/notifications'
      fullPath: '/creator/notifications/'
      preLoaderRoute: typeof CreatorNotificationsIndexRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/portfolio/': {
      id: '/creator/portfolio/'
      path: '/portfolio'
      fullPath: '/creator/portfolio/'
      preLoaderRoute: typeof CreatorPortfolioIndexRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/profile/': {
      id: '/creator/profile/'
      path: '/profile'
      fullPath: '/creator/profile/'
      preLoaderRoute: typeof CreatorProfileIndexRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/projects/': {
      id: '/creator/projects/'
      path: '/projects'
      fullPath: '/creator/projects/'
      preLoaderRoute: typeof CreatorProjectsIndexRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/services/': {
      id: '/creator/services/'
      path: '/services'
      fullPath: '/creator/services/'
      preLoaderRoute: typeof CreatorServicesIndexRouteImport
      parentRoute: typeof CreatorRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCreatorApplicationsIdRoute: typeof AdminCreatorApplicationsIdRoute
  AdminCreatorsIdRoute: typeof AdminCreatorsIdRoute
  AdminAuditLogsIndexRoute: typeof AdminAuditLogsIndexRoute
  AdminClientsIndexRoute: typeof AdminClientsIndexRoute
  AdminCreatorApplicationsIndexRoute: typeof AdminCreatorApplicationsIndexRoute
  AdminCreatorTiersIndexRoute: typeof AdminCreatorTiersIndexRoute
  AdminCreatorsIndexRoute: typeof AdminCreatorsIndexRoute
  AdminProjectsIndexRoute: typeof AdminProjectsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminCreatorApplicationsIdRoute: AdminCreatorApplicationsIdRoute,
  AdminCreatorsIdRoute: AdminCreatorsIdRoute,
  AdminAuditLogsIndexRoute: AdminAuditLogsIndexRoute,
  AdminClientsIndexRoute: AdminClientsIndexRoute,
  AdminCreatorApplicationsIndexRoute: AdminCreatorApplicationsIndexRoute,
  AdminCreatorTiersIndexRoute: AdminCreatorTiersIndexRoute,
  AdminCreatorsIndexRoute: AdminCreatorsIndexRoute,
  AdminProjectsIndexRoute: AdminProjectsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CreatorRouteChildren {
  CreatorIndexRoute: typeof CreatorIndexRoute
  CreatorEarningsIndexRoute: typeof CreatorEarningsIndexRoute
  CreatorNotificationsIndexRoute: typeof CreatorNotificationsIndexRoute
  CreatorPortfolioIndexRoute: typeof CreatorPortfolioIndexRoute
  CreatorProfileIndexRoute: typeof CreatorProfileIndexRoute
  CreatorProjectsIndexRoute: typeof CreatorProjectsIndexRoute
  CreatorServicesIndexRoute: typeof CreatorServicesIndexRoute
}

const CreatorRouteChildren: CreatorRouteChildren = {
  CreatorIndexRoute: CreatorIndexRoute,
  CreatorEarningsIndexRoute: CreatorEarningsIndexRoute,
  CreatorNotificationsIndexRoute: CreatorNotificationsIndexRoute,
  CreatorPortfolioIndexRoute: CreatorPortfolioIndexRoute,
  CreatorProfileIndexRoute: CreatorProfileIndexRoute,
  CreatorProjectsIndexRoute: CreatorProjectsIndexRoute,
  CreatorServicesIndexRoute: CreatorServicesIndexRoute,
}

const CreatorRouteWithChildren =
  CreatorRoute._addFileChildren(CreatorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ClientRoute: ClientRoute,
  ContactRoute: ContactRoute,
  CreatorRoute: CreatorRouteWithChildren,
  CreatorApplyRoute: CreatorApplyRoute,
  CreatorsRoute: CreatorsRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
